import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const dist = path.join(root, 'dist');
const pub = path.join(dist, 'public');
const priv = path.join(dist, 'private');
const buildVersion = '13.4.0';
const buildId = `v${buildVersion}-hostinger-private-json-${new Date().toISOString().slice(0,10).replaceAll('-','')}`;
const configSourcePath = path.join(root, '.autoklinika-private-config.json');

const exists = async (p) => { try { await fs.access(p); return true; } catch { return false; } };
const copy = async (from, to) => {
  if (!(await exists(from))) return;
  await fs.cp(from, to, { recursive: true, force: true });
};

let privateConfig;
if (await exists(configSourcePath)) {
  privateConfig = JSON.parse(await fs.readFile(configSourcePath, 'utf8'));
} else {
  privateConfig = {
    adminLogin: 'admin',
    adminPassword: `AK-${crypto.randomBytes(12).toString('base64url')}`,
    captchaSecret: crypto.randomBytes(32).toString('hex'),
    mailTo: 'autoklinikagorzyn@gmail.com',
    timezone: 'Europe/Warsaw',
  };
  await fs.writeFile(configSourcePath, JSON.stringify(privateConfig, null, 2) + '\n', 'utf8');
}

for (const k of ['adminLogin','adminPassword','captchaSecret','mailTo','timezone']) {
  if (!privateConfig[k]) throw new Error(`Brak ${k} w .autoklinika-private-config.json`);
}

await fs.rm(dist, { recursive: true, force: true });
await fs.mkdir(pub, { recursive: true });
await fs.mkdir(priv, { recursive: true });

const publicFiles = [
  'index.html', 'cennik.html', 'polityka-prywatnosci.html', 'cookies.html',
  'ustawienia-cookies.html', 'informacje-prawne.html',
];
for (const file of publicFiles) await copy(path.join(root, file), path.join(pub, file));
for (const dir of ['assets','src','administrator','uploads']) await copy(path.join(root, dir), path.join(pub, dir));
await copy(path.join(root, 'production', 'api'), path.join(pub, 'api'));
await fs.copyFile(path.join(root, 'production', 'public.htaccess'), path.join(pub, '.htaccess'));

await fs.copyFile(path.join(root, 'data', 'default_content.json'), path.join(priv, 'default_content.json'));
await fs.copyFile(path.join(root, 'production', 'private', '.htaccess'), path.join(priv, '.htaccess'));

const phpEscape = (s) => String(s).replaceAll('\\', '\\\\').replaceAll("'", "\\'");
const passHash = crypto.createHash('sha256').update(privateConfig.adminPassword, 'utf8').digest('hex');
const configPhp = `<?php\n// Generated by npm run build. Keep this file outside public_html.\nreturn [\n  'build' => '${phpEscape(buildId)}',\n  'admin_login' => '${phpEscape(privateConfig.adminLogin)}',\n  'admin_password_sha256' => '${passHash}',\n  'captcha_secret' => '${phpEscape(privateConfig.captchaSecret)}',\n  'mail_to' => '${phpEscape(privateConfig.mailTo)}',\n  'timezone' => '${phpEscape(privateConfig.timezone)}',\n];\n`;
await fs.writeFile(path.join(priv, 'config.php'), configPhp, 'utf8');
await fs.writeFile(path.join(priv, 'ADMIN_LOGIN.txt'), `AutoKlinika CMS — dane administratora\n\nLogin: ${privateConfig.adminLogin}\nHasło: ${privateConfig.adminPassword}\n\nPanel: https://autoklinika.org/administrator/\n\nTen plik musi pozostać w katalogu private, poza public_html.\n`, 'utf8');
await fs.writeFile(path.join(priv, 'README.txt'), `AUTOKLINIKA — PRIVATE\n\nTen katalog umieść OBOK public_html, nie w public_html.\nNie twórz ręcznie bazy ani tabel. Backend PHP sam utworzy katalog runtime i pliki JSON przy pierwszym wejściu na stronę.\n\nZawartość runtime przechowuje m.in. zgłoszenia, CMS, analitykę i log wysyłki e-mail. Przy kolejnych aktualizacjach NIE USUWAJ katalogu private/runtime.\n\nPowiadomienia formularza są wysyłane przez funkcję mail() hostingu na: ${privateConfig.mailTo}\n`, 'utf8');

const entries = await fs.readdir(dist);
if (entries.sort().join(',') !== 'private,public') throw new Error('dist powinien zawierać wyłącznie katalogi public i private.');

console.log('');
console.log('=============================================');
console.log('  AutoKlinika WWW — BUILD HOSTINGER');
console.log('=============================================');
console.log(`Build:      ${buildId}`);
console.log(`PUBLIC:     ${path.relative(root, pub)}`);
console.log(`PRIVATE:    ${path.relative(root, priv)}`);
console.log('');
console.log('Hostinger:');
console.log('  1) zawartość dist/public  -> public_html');
console.log('  2) katalog dist/private   -> obok public_html jako private');
console.log('');
console.log(`CMS login:  ${privateConfig.adminLogin}`);
console.log(`CMS hasło:  ${privateConfig.adminPassword}`);
console.log('Kopia danych logowania: dist/private/ADMIN_LOGIN.txt');
console.log('');
console.log('Nie jest potrzebny MySQL, SQLite, Composer ani npm na serwerze.');
